name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v2
    - name: Run Hello World!
      run: echo Hello, World!
